name: 'Add Smartsheet Row'
description: 'Adds a new row to a Smartsheet'
branding:
  icon: 'file-plus'
  color: 'blue'
inputs:
  access-token:
    description: 'Smartsheet API access token'
    required: true
  sheet-id:
    description: 'Smartsheet sheet ID'
    required: true
outputs:
  row-id:
    description: 'ID of the created row'
runs:
  using: 'node12'
  main: 'dist/index.js'
