name: Test

on:
  push:
    branches:
    - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: paulholden2/smartsheet-add-row@v1
      with:
        row-data:
        - column_id: 1234
          value: '1234 value'
        - column_id: 4321
          value: '4321 value'
