name: Test

on:
  push:
    branches:
    - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: paulholden2/smartsheet-add-row@v1
      with:
        api-key: ${{ secrets.SMARTSHEET_API_KEY }}
        sheet-id: ${{ secrets.SMARTSHEET_SHEET_ID }}
